- name: Copy build files
  become: true 
  copy:
    # src: "../../../../../artifact.tar.gz"
    src: ~/project/artifact.tar.gz
    dest: /
    owner: ubuntu
    group: ubuntu        
    mode: 0644

- name: Extraxt build files
  become: true 
  shell: |
    tar -xf artifact.tar.gz

- name: Executing deploy
  become: true 
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start