- name: Copy build files
  become: true 
  copy:
    # src: "../../../../../artifact.tar.gz"
    src: ~/project/artifact.tar.gz
    dest: ~/
    owner: ubuntu
    group: ubuntu        
    mode: 0644

- name: Executing deploy
  become: true 
  shell: |
    cd /var
    tar -xf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start