- name: Copy build files
  become: true 
  copy:
    # src: "../../../../../artifact.tar.gz"
    src: ~/project/artifact.tar.gz
    dest: /var/www/html
    owner: apache
    group: apache        
    mode: 0644

- name: Executing deploy
  shell: |
    cd /var/www/html
    tar -xf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start