---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm", "python3"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy project files
  become: true 
  copy:
    # src: "../../../../../artifact.tar.gz"
    src: ~/project/artifact.tar.gz
    dest: "/var"
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Executing deploy
  become: true 
  shell: |
    cd /var
    tar -xf artifact.tar.gz
    npm install
    # pm2 stop default
    # pm2 start npm -- start:prod
    pm2 start node ./dist/main.js

# - name: Executing deploy
#   become: true 
#   shell: |
#     cd /web
#     pm2 start ~/web/main.js -f