- name: Copy build files
  template:
    # src: "../../../../../artifact.tar.gz"
    src: "~/project/artifact.tar.gz"
    dest: "~/"

- name: Executing deploy
  shell: |
    tar -xf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start