---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Creates directory
  file:
    path: ~/project
    state: directory

- name: Copy build files
  become: true 
  copy:
    src: ~/project/backend/./dist/
    dest: "/web"
    owner: ubuntu
    group: ubuntu   
    mode: 0755

- name: Copy project files
  become: true 
  copy:
    # src: "../../../../../artifact.tar.gz"
    src: ~/project/artifact.tar.gz
    dest: "/project"
    owner: ubuntu
    group: ubuntu   
    mode: 0755

- name: Executing deploy
  become: true 
  shell: |
    cd project
    tar -xf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start

- name: Executing deploy
  become: true 
  shell: |
    pm2 start ~/web/main.js -f